### ISSUE TITLE
友盟官方是把没安装的应用隐藏掉

### ISSUE THREAD

**Issue by sdqdChen** [srxboys/RXUMDemo#3]
“为避免应用审核被拒，仅会对有效的平台进行显示，如平台应用未安装，或平台应用不支持等会进行隐藏。”你写的这个没有实现啊

**Comment by srxboys** [comment]
https://github.com/srxboys/RXUMDemo/commit/2e8f1f318233d2d231af0bc85d1f7b34d7170e84
你看这个
